version: '3.4'

services:
  carmd.shell.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:5003
    networks:
      shell_api_kiosk_network:
         ipv4_address: 172.123.1.1
    expose:
      - "5003"
    volumes:
      - .\CarMD.Shell.Api\Log:C:\app\log
      - .\CarMD.Shell.Api\db:C:\app\db
      - .\CarMD.Shell.Api\Library:C:\app\Library
      - .\CarMD.Shell.Api\Manufacturers:C:\app\Manufacturers
      - .\CarMD.Shell.Api\Winimage:C:\app\Winimage
networks:
  shell_api_kiosk_network:
    ipam:
      driver: default
      config:
         - subnet: 172.123.0.0/16