# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
    - action-test
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Runs a set of commands using the runners shell
    - name: Add SSH Credentials
      uses: shimatoro/ssh-key-action@v2
      with:
        key: ${{ secrets.KEY }} # required, this will be used when transferring files to your deploy targets
        known_hosts: ${{ secrets.HOST }} # required, should match up with your deploy targets (see below)
      
    # Step 3: Deploy!
    - name: Deploy to Staging
      uses: JorgenVatle/docker-compose-deploy@v1.0
      with:
        deploy_targets: ${{ secrets.HOST }} # required, comma separated list of servers to deploy to.

        ssh_user: ${{ secrets.USERNAME }} # optional, user to connect to deploy targets with. Defaults to 'root'
        compose_file: 'docker-compose.yml' # optional, path/filename of your docker-compose file. Defaults to 'docker-compose.yml'
        validate_container: 'carmd.shell.api' # optional, validate that the given container name is running. Otherwise, throw an error. Defaults to 'app' 
